name: Upload to release

on:
  release:
    types: created

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install deps
        run: npm install

      - name: Get release event
        id: upload_existing_release_asset
        uses: ./.github/actions/output-event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./dist/my-artifact.zip
          asset_name: my-artifact.zip
          asset_content_type: application/zip

      - name: Add NPM auth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_API_KEY }}" > ~/.npmrc
      
      - name: Publish package
        run: npm publish
          