name: PR

on: pull_request

jobs:
  build:
    name: Pull request
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Run linting
      run: npm run lint
    - name: Run tests
      run: npm test
    